# permissions for end users to edit foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-editor-role
rules:
- apiGroups:
  - samplecontroller.ishishow.com
  resources:
  - foos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplecontroller.ishishow.com
  resources:
  - foos/status
  verbs:
  - get
